version: '3'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn:2.3
    container_name: openvpn
    ports:
     - "${HOST_PORT}:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
